name: Build GraphWar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Compilar
        run: |
          chmod +x compile.sh
          ./compile.sh

      - name: Guardar JARs
        uses: actions/upload-artifact@v4
        with:
          name: graphwar-jars
          path: |
            graphwar.jar
            roomServer.jar
            globalServer.jar
